### ISSUE TITLE
Lost string

### ISSUE THREAD

**Issue by creold** [joshbduncan/ExtendScript-Compiler#1]
@joshbduncan after compilation, the last line is always removed from the original code. Example of my script.
```js
#includepath "lib/" // Libraries folder
#include "base.jsx" // Base small functions
#include "generator.jsx" // Generator functions

function main() {
... // some code
}

// Run script
try {
  main();
} catch (err) {}
```
I'm getting this
```js
... // included libs

function main() {
... // some code
}

// Run script
try {
  main();
```
![lost-string](https://user-images.githubusercontent.com/32217031/192442238-154afa2b-0956-45b9-8c27-a68b9339f748.jpg)

**Comment by joshbduncan** [comment]
Hmmm, that's weird... Let me look into it and see if I can figure it out.

**Comment by joshbduncan** [comment]
@creold, so it seems your file has an incomplete last line... My editor is setup to add a blank new line to the end of every file I save so I would have never noticed it. If I just cat out your code with the -e (show invisible characters) flag you can see the last line doesn't have a '$'...  This means there is no new line '\n' character there so my script skips it. I found a [deeper explanation here](https://unix.stackexchange.com/questions/482517/why-does-this-while-loop-not-recognize-the-last-line).

![Screen Shot 2022-09-27 at 11 24 18](https://user-images.githubusercontent.com/44387852/192568808-c1b2e2d4-77f5-43df-8701-b8522c67d1f0.png)

It's a simple fix on my end, so I just pushed an update that should work for you...

As a side note, not having that last newline character in your included files would also cause them to bunch up like below.

```javascript
// base.jsx
// some
// lines
// last line base.jsx// generator.jsx
// some
// lines
// last line generator.jsx
function main() {
  //...
}
````

Notice how the last line of base.jsx is together with the first line of generator.jsx. That's because that newline character isn't on the last line. I fixed this too by checking if the file has a '\n' character on the last line and if not, the script just adds it in the output.

I recreated your files and tested them on my and all worked for me but try it on your system and let me know if you get the correct results.

```bash
$./compile.sh sample/script.jsx                                                        
// base.jsx
// some
// lines
// last line base.jsx
// generator.jsx
// some
// lines
// last line generator.jsx

function main() {
  alert(app);
}

// Run script
try {
  main();
} catch (err) {}
```

**Comment by creold** [comment]
@joshbduncan it looks pretty damn good. I compiled two different scripts with libraries. This saves a lot of time
